[package]
name = "mqtt-push"
version = "0.1.0"
authors = ["Max Gortman <mgortman@microsoft.com>"]

[dependencies]
tokio-io = "=0.1.5"
tokio-core = "=0.1.12"
tokio-proto = "0.1"
tokio-service = "0.1"
mqtt = { git = "https://github.com/nayato/rust-mqtt", branch = "owned" }
string = { git = 'https://github.com/carllerche/string' }
net2 = "*"
num_cpus = "1"
native-tls = "*"
clap = "2"
bytes="*"
time="*"
rustls = "*"
tokio-timer = "*"
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }
uuid = { version = "*", features = ["use_std", "v4"] }
tokio-rustls = { version = "*", features = ["tokio-proto"] }
tokio-tls = { version = "*", features = ["tokio-proto"] }

[profile.release]
debug = true

[patch.crates-io]
futures-await = { git = 'https://github.com/golddranks/futures-await', rev = '5b24904cab8e7668f12c074b735939e6916f0b54'} #{ git = 'https://github.com/alexcrichton/futures-await' }
futures-await-async-macro = { git = 'https://github.com/golddranks/futures-await', rev = '5b24904cab8e7668f12c074b735939e6916f0b54'} #{ git = 'https://github.com/alexcrichton/futures-await' }
futures-await-await-macro = { git = 'https://github.com/golddranks/futures-await', rev = '5b24904cab8e7668f12c074b735939e6916f0b54'} #{ git = 'https://github.com/alexcrichton/futures-await' }

[patch."https://github.com/alexcrichton/futures-await"]
futures-await = { git = 'https://github.com/golddranks/futures-await', rev = '5b24904cab8e7668f12c074b735939e6916f0b54'} #{ git = 'https://github.com/alexcrichton/futures-await' }
futures-await-async-macro = { git = 'https://github.com/golddranks/futures-await', rev = '5b24904cab8e7668f12c074b735939e6916f0b54'} #{ git = 'https://github.com/alexcrichton/futures-await' }
futures-await-await-macro = { git = 'https://github.com/golddranks/futures-await', rev = '5b24904cab8e7668f12c074b735939e6916f0b54'} #{ git = 'https://github.com/alexcrichton/futures-await' }
